import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (

    <div className={styles.container}>

      <Head>

        <title>Create Next App - Test</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.wrapperMain}>
        
      <h2 className={styles.heading}>Todo App</h2>

        <div className={styles.linkMainWrapper}>

          <Link className={styles.linkMain} href='/todo/form'>Form Add Todo</Link>

          <Link className={styles.linkMain} href='/todo/1'>Todo List</Link>

        </div>

        
        
      </main>

  
    </div>

  )

}

export default Home
